spring.application.name=skyisyours-apis

# PostgreSQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sky_is_yours
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=nishanth
spring.datasource.password=mysecretpw

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Error Response Attributes
server.error.include-message=always
server.error.include-binding-errors=always